#!/system/bin/sh

UNINSTALL="
com.miui.phrase
com.google.android.gms.location.history
com.miui.bugreport
com.miui.thirdappassistant
com.unionpay.tsmservice.mi
com.miui.hybrid
com.google.android.marvin.talkback
com.miui.yellowpage
com.android.adservices.api
com.xiaomi.aiasst.service
com.miui.analytics
com.mediatek.atmwifimeta
com.android.bluetoothmidiservice
com.android.browser
com.android.calllogbackup
com.xiaomi.cameratools
com.miui.carlink
com.miui.cloudbackup
com.android.health.connect.backuprestore
com.android.inputsettings.overlay.miui
com.android.managedprovisioning.overlay
com.android.microdroid.empty_payload
com.android.ondevicepersonalization.services
com.android.overlay.gmscontactprovider
com.android.overlay.gmssettingprovider
com.android.overlay.gmssettings
com.android.overlay.gmstelecomm
com.android.overlay.gmstelephony
com.android.providers.partnerbookmarks
com.android.settings.overlay.miui
com.android.stk.overlay.miui
com.android.systemui.overlay.miui
com.android.virtualmachine.res
com.google.android.cellbroadcastreceiver.overlay.miui
com.google.android.cellbroadcastservice.overlay.miui
com.miui.miwallpaper.overlay.customize
com.miui.settings.rro.device.type.overlay
com.miui.system.overlay
com.miui.voiceassistoverlay
com.miui.wallpaper.overlay.customize
com.debug.loggerui
com.xiaomi.mirror
com.xiaomi.digitalkey
com.miui.greenguard
com.xiaomi.location.fused
com.goodix.fingerprint.setting
com.google.android.onetimeinitializer
com.android.healthconnect.controller
com.mediatek.lbs.em2.ui
com.miui.vsimcore
com.mediatek.mdmconfig
com.miui.voiceassist
com.xiaomi.aiasst.vision
com.xiaomi.payment
com.xiaomi.mi_connect.service
com.miui.accessibility
com.miui.securityinputmethod
com.xiaomi.ab
com.miui.micloudsync
com.xiaomi.metoknlp
com.xiaomi.otrpbroker
com.android.quicksearchbox
com.xiaomi.security.onetrack
com.miui.tsmclient
com.miui.nextpay
com.tencent.soter.soterserver
com.miui.daemon
com.android.traceur
com.miui.uireporter
com.miui.voicetrigger
com.xiaomi.aireco
com.miui.cloudservice
com.xiaomi.mis
com.sohu.inputmethod.sogou.xiaomi
com.miui.systemAdSolution
com.xiaomi.gamecenter.sdk.service
com.miui.contentcatcher
com.xiaomi.barrage
com.android.federatedcompute.services
com.android.systemui.accessibility.accessibilitymenu
com.mediatek.MtkSettingsResOverlay
com.mediatek.SettingsProviderResOverlay
com.mediatek.voiceunlock
com.miui.securitycenter.securitycenter_phone_overlay.config.overlay
com.miui.settings.rro.device.hide.statusbar.overlay
com.xiaomi.touchservice
com.miui.newhome
org.ifaa.aidl.manager
com.iflytek.inputmethod.miui
com.mediatek.magtapp
com.mediatek.mdmlsample
com.xiaomi.mibrain.speech
com.xiaomi.mi_connect_service
cn.wps.moffice_eng.xiaomi.lite
com.miui.newmidrive
com.mfashiongallery.emag
com.xiaomi.macro
com.xiaomi.trustservice
"

for pkg in $UNINSTALL; do
    su -c "pm uninstall -k --user 0 $pkg"
done
